# connect-fw-to-cdl.xml -- Ansible playbook to run a few commands needed to connect firewalls to CDL
#   Author: Tyson Reed, no implied warranty. Released under GPL
#   v0.1 - February 12, 2021
#
# REQUIRES
# ansible (v 2.9) (sudo apt-add-respository --yes ppa:ansible/ansible ; sudo apt update ; sudo apt install ansible)
# palo role (sudo ansible-galaxy collection install paloaltonetworks.panos)
# python (tested with version 2.7.12)
# python pip (tested with version 8.1.1 for 2.7) 
# pandevice python package (sudo -H pip install pandevice)
#
#
# STEPS
# update vars.yml with valid user/password
# update hosts with list of firewall ip addresses
# update ansible_python_interpreter below with location of python
#
# EXECUTE
# ansible-playbook -i hosts connect-fw-to-cdl.yml
#
---
- name: RUN A FEW CDL COMMANDS ON FIREWALLS
  hosts: all
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:

  - name: get credentials from file
    include_vars: "vars.yml"
    no_log: "yes"

  - name: connect to each firewall and run command 'delete license key <logging service key>'
    panos_op:
      provider: "{{ fw }}"
      cmd: "delete license key Log*"
    register: panos

  - name: connect to each firewall and run command 'request license fetch'
    panos_op:
      provider: "{{ fw }}"
      cmd: "request license fetch"
    register: panos

  - name: connect to each firewall and run command 'request logging-service-forwarding certificate delete'
    panos_op:
      provider: "{{ fw }}"
      cmd: "request logging-service-forwarding certificate delete"
    register: panos

  - name: connect to each firewall and run command 'request logging-service-forwarding certificate fetch'
    panos_op:
      provider: "{{ fw }}"
      cmd: "request logging-service-forwarding certificate fetch"
    register: panos

